//! One fail-closed quality policy for local and CI execution.
mod attribute_policy;
mod attribute_validation;
pub mod ci;
pub mod contracts;
pub mod coupling;
mod derive_identity;
pub mod driver;
pub mod environment;
pub mod inventory;
pub mod macro_policy;
pub mod measurement;
pub mod measurements;
pub mod metrics;
mod module_bindings;
pub mod modules;
pub mod policy;
mod quote_identity;
pub mod scan;
pub mod suppression;
pub mod type_aggregate;
